apiVersion: skaffold/v1beta2
kind: Config
build:
  artifacts:
  - image: changeme
    context: .
    docker: {}
  tagPolicy:
    envTemplate:
      template: '{{.DOCKER_REGISTRY}}/q131172019/nodejs-canary:{{.VERSION}}'
  local: {}
deploy:
  kubectl: {}
profiles:
- name: dev
  build:
    artifacts:
    - docker: {}
    tagPolicy:
      envTemplate:
        template: '{{.DOCKER_REGISTRY}}/q131172019/nodejs-canary:{{.DIGEST_HEX}}'
    local: {}
  deploy:
    helm:
      releases:
      - name: nodejs-canary
        chartPath: charts/nodejs-canary
        setValueTemplates:
          image.repository: '{{.DOCKER_REGISTRY}}/q131172019/nodejs-canary'
          image.tag: '{{.DIGEST_HEX}}'
